#!/usr/bin/env python

import optparse
import sys
from nltk import word_tokenize

optparser = optparse.OptionParser()
optparser.add_option("-i", "--input", dest="trans_lm_file", default="../../data/translations.tsv", help="MTurk translations file with language model probabilities")
optparser.add_option("-f", "--feat", dest="trans_feat", default="../../data/turk_translations_features_5.tsv", help="MTurk translations feature file")
opts = optparser.parse_args()[0]


all_hyps = [line.split('\t')[6:10] for line in open(opts.trans_lm_file)]
all_feats = [line.strip().split('\t') for line in open(opts.trans_feat)][1:]

for (ind,hyp) in enumerate(all_hyps[1:]):
    sents = hyp[0:4]

    max_ind = -1
    max_score = -1*sys.maxint

    for (t_no,tran) in enumerate(sents) :
        feat_for_one_tran = all_feats[ind][t_no*22:t_no*22+22]

        if len(word_tokenize(tran)) < 2 or "NO TRANSLATION FOUND" in tran or "n/a" in tran:
             feat_for_one_tran[0] = 10000
             feat_for_one_tran[1] = 10000

        score = 0.0

        # Compute Score using features
        # YOUR CODE GOES HERE


        if score > max_score:
            max_score = score
            max_ind = t_no

    print sents[max_ind]
